/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StudySession {
  'hours' : number,
  'subjectName' : string,
  'date' : string,
}
export interface Subject {
  'id' : bigint,
  'days' : Array<boolean>,
  'name' : string,
  'description' : string,
  'isWeak' : boolean,
}
export interface SubjectQuestionProgress {
  'subjectName' : string,
  'count' : bigint,
}
export interface _SERVICE {
  'addMockScore' : ActorMethod<[bigint], undefined>,
  'addQuestions' : ActorMethod<[string, bigint], undefined>,
  'addStudySession' : ActorMethod<[string, number, string], undefined>,
  'addSubject' : ActorMethod<[string, string], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getMockScores' : ActorMethod<[], Array<bigint>>,
  'getQuestionProgress' : ActorMethod<[], Array<SubjectQuestionProgress>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'toggleDay' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];