/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExamSession {
  'id' : bigint,
  'completedAt' : string,
  'subject' : string,
  'difficulty' : string,
  'timeTakenSeconds' : bigint,
  'totalQuestions' : bigint,
  'correctAnswers' : bigint,
}
export interface FileMetadata {
  'id' : bigint,
  'blobUrl' : string,
  'mimeType' : string,
  'fileName' : string,
  'sizeBytes' : bigint,
  'uploadedAt' : string,
}
export interface MonthlyLogEntry { 'date' : string, 'count' : bigint }
export interface NotebookEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : string,
  'createdAt' : string,
  'updatedAt' : string,
}
export interface NotepadEntry {
  'id' : bigint,
  'content' : string,
  'subject' : string,
  'createdAt' : string,
  'updatedAt' : string,
}
export interface Question {
  'id' : bigint,
  'subject' : string,
  'difficulty' : string,
  'createdAt' : string,
  'correctAnswer' : string,
  'questionText' : string,
  'questionType' : string,
  'options' : Array<string>,
}
export interface StudySession {
  'hours' : number,
  'subjectName' : string,
  'date' : string,
}
export interface Subject {
  'id' : bigint,
  'days' : Array<boolean>,
  'name' : string,
  'description' : string,
  'isWeak' : boolean,
}
export interface SubjectQuestionProgress {
  'subjectName' : string,
  'count' : bigint,
}
export interface SubjectTarget { 'name' : string, 'target' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserTargets {
  'dailyStudyHoursTarget' : number,
  'subjectTargets' : Array<SubjectTarget>,
  'planTotalDays' : bigint,
  'totalQuestionsGoal' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMockScore' : ActorMethod<[bigint], undefined>,
  'addNotebookEntry' : ActorMethod<[string, string, string, string], undefined>,
  'addNotepadEntry' : ActorMethod<[string, string, string], undefined>,
  'addQuestion' : ActorMethod<
    [string, string, string, Array<string>, string, string, string],
    undefined
  >,
  'addQuestions' : ActorMethod<[string, bigint], undefined>,
  'addStudySession' : ActorMethod<[string, number, string], undefined>,
  'addSubject' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFileMetadata' : ActorMethod<[bigint], undefined>,
  'deleteNotebookEntry' : ActorMethod<[bigint], undefined>,
  'deleteNotepadEntry' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAllFileMetadata' : ActorMethod<[], Array<FileMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamSessions' : ActorMethod<[], Array<ExamSession>>,
  'getMockScores' : ActorMethod<[], Array<bigint>>,
  'getMonthlyLogs' : ActorMethod<[], Array<MonthlyLogEntry>>,
  'getNotebookEntries' : ActorMethod<[], Array<NotebookEntry>>,
  'getNotepadEntries' : ActorMethod<[], Array<NotepadEntry>>,
  'getQuestionProgress' : ActorMethod<[], Array<SubjectQuestionProgress>>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestionsBySubject' : ActorMethod<[string], Array<Question>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTargets' : ActorMethod<[], UserTargets>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExamSession' : ActorMethod<
    [string, bigint, bigint, bigint, string, string],
    undefined
  >,
  'saveFileMetadata' : ActorMethod<
    [string, string, bigint, string, string],
    bigint
  >,
  'saveMonthlyLog' : ActorMethod<[string, bigint], undefined>,
  'setQuestionCount' : ActorMethod<[string, bigint], undefined>,
  'setStudySession' : ActorMethod<[string, number, string], undefined>,
  'setTargets' : ActorMethod<
    [bigint, number, Array<SubjectTarget>, bigint],
    undefined
  >,
  'toggleDay' : ActorMethod<[bigint, bigint], undefined>,
  'updateNotebookEntry' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateNotepadEntry' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];