/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectQuestionProgress = IDL.Record({
  'subjectName' : IDL.Text,
  'count' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'hours' : IDL.Float64,
  'subjectName' : IDL.Text,
  'date' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'days' : IDL.Vec(IDL.Bool),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isWeak' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addMockScore' : IDL.Func([IDL.Nat], [], []),
  'addQuestions' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addStudySession' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getMockScores' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getQuestionProgress' : IDL.Func(
      [],
      [IDL.Vec(SubjectQuestionProgress)],
      ['query'],
    ),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'toggleDay' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectQuestionProgress = IDL.Record({
    'subjectName' : IDL.Text,
    'count' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'hours' : IDL.Float64,
    'subjectName' : IDL.Text,
    'date' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'days' : IDL.Vec(IDL.Bool),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isWeak' : IDL.Bool,
  });
  
  return IDL.Service({
    'addMockScore' : IDL.Func([IDL.Nat], [], []),
    'addQuestions' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addStudySession' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getMockScores' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getQuestionProgress' : IDL.Func(
        [],
        [IDL.Vec(SubjectQuestionProgress)],
        ['query'],
      ),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'toggleDay' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };