/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileMetadata = IDL.Record({
  'id' : IDL.Nat,
  'blobUrl' : IDL.Text,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'uploadedAt' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExamSession = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Text,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'timeTakenSeconds' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
});
export const MockTestScore = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'score' : IDL.Nat,
});
export const MonthlyLogEntry = IDL.Record({
  'date' : IDL.Text,
  'count' : IDL.Nat,
});
export const NotebookEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Text,
  'updatedAt' : IDL.Text,
});
export const NotepadEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Text,
  'updatedAt' : IDL.Text,
});
export const Section = IDL.Variant({
  'studyplan' : IDL.Null,
  'questions' : IDL.Null,
  'dailyroutine' : IDL.Null,
});
export const SectionPlanCycle = IDL.Record({
  'endDate' : IDL.Text,
  'section' : Section,
  'summary' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const SubjectQuestionProgress = IDL.Record({
  'subjectName' : IDL.Text,
  'count' : IDL.Nat,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'createdAt' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'questionType' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const SectionTimeLog = IDL.Record({
  'date' : IDL.Text,
  'section' : Section,
  'elapsedSeconds' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'hours' : IDL.Float64,
  'subjectName' : IDL.Text,
  'date' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'days' : IDL.Vec(IDL.Bool),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isWeak' : IDL.Bool,
});
export const SubjectTarget = IDL.Record({
  'name' : IDL.Text,
  'target' : IDL.Nat,
});
export const UserTargets = IDL.Record({
  'dailyStudyHoursTarget' : IDL.Float64,
  'subjectTargets' : IDL.Vec(SubjectTarget),
  'planTotalDays' : IDL.Nat,
  'totalQuestionsGoal' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMockScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addNotebookEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addNotepadEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addQuestions' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addStudySession' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFileMetadata' : IDL.Func([IDL.Nat], [], []),
  'deleteNotebookEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteNotepadEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAllFileMetadata' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getExamSessions' : IDL.Func([], [IDL.Vec(ExamSession)], ['query']),
  'getMockScores' : IDL.Func([], [IDL.Vec(MockTestScore)], ['query']),
  'getMonthlyLogs' : IDL.Func([], [IDL.Vec(MonthlyLogEntry)], ['query']),
  'getNotebookEntries' : IDL.Func([], [IDL.Vec(NotebookEntry)], ['query']),
  'getNotepadEntries' : IDL.Func([], [IDL.Vec(NotepadEntry)], ['query']),
  'getPlanCycles' : IDL.Func([], [IDL.Vec(SectionPlanCycle)], ['query']),
  'getQuestionProgress' : IDL.Func(
      [],
      [IDL.Vec(SubjectQuestionProgress)],
      ['query'],
    ),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getSectionTimeLogs' : IDL.Func([], [IDL.Vec(SectionTimeLog)], ['query']),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTargets' : IDL.Func([], [UserTargets], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExamSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveFileMetadata' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveMonthlyLog' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'savePlanCycle' : IDL.Func([Section, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'saveSectionTimeLog' : IDL.Func([Section, IDL.Text, IDL.Nat], [], []),
  'setCustomSubjects' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setQuestionCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setStudySession' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
  'setTargets' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Vec(SubjectTarget), IDL.Nat],
      [],
      [],
    ),
  'toggleDay' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateNotebookEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNotepadEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'id' : IDL.Nat,
    'blobUrl' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'uploadedAt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExamSession = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Text,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'timeTakenSeconds' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
  });
  const MockTestScore = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'score' : IDL.Nat,
  });
  const MonthlyLogEntry = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const NotebookEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Text,
    'updatedAt' : IDL.Text,
  });
  const NotepadEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Text,
    'updatedAt' : IDL.Text,
  });
  const Section = IDL.Variant({
    'studyplan' : IDL.Null,
    'questions' : IDL.Null,
    'dailyroutine' : IDL.Null,
  });
  const SectionPlanCycle = IDL.Record({
    'endDate' : IDL.Text,
    'section' : Section,
    'summary' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const SubjectQuestionProgress = IDL.Record({
    'subjectName' : IDL.Text,
    'count' : IDL.Nat,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'createdAt' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'questionType' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const SectionTimeLog = IDL.Record({
    'date' : IDL.Text,
    'section' : Section,
    'elapsedSeconds' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'hours' : IDL.Float64,
    'subjectName' : IDL.Text,
    'date' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'days' : IDL.Vec(IDL.Bool),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isWeak' : IDL.Bool,
  });
  const SubjectTarget = IDL.Record({ 'name' : IDL.Text, 'target' : IDL.Nat });
  const UserTargets = IDL.Record({
    'dailyStudyHoursTarget' : IDL.Float64,
    'subjectTargets' : IDL.Vec(SubjectTarget),
    'planTotalDays' : IDL.Nat,
    'totalQuestionsGoal' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMockScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addNotebookEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addNotepadEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addQuestions' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addStudySession' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFileMetadata' : IDL.Func([IDL.Nat], [], []),
    'deleteNotebookEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteNotepadEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAllFileMetadata' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getExamSessions' : IDL.Func([], [IDL.Vec(ExamSession)], ['query']),
    'getMockScores' : IDL.Func([], [IDL.Vec(MockTestScore)], ['query']),
    'getMonthlyLogs' : IDL.Func([], [IDL.Vec(MonthlyLogEntry)], ['query']),
    'getNotebookEntries' : IDL.Func([], [IDL.Vec(NotebookEntry)], ['query']),
    'getNotepadEntries' : IDL.Func([], [IDL.Vec(NotepadEntry)], ['query']),
    'getPlanCycles' : IDL.Func([], [IDL.Vec(SectionPlanCycle)], ['query']),
    'getQuestionProgress' : IDL.Func(
        [],
        [IDL.Vec(SubjectQuestionProgress)],
        ['query'],
      ),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getSectionTimeLogs' : IDL.Func([], [IDL.Vec(SectionTimeLog)], ['query']),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTargets' : IDL.Func([], [UserTargets], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExamSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveFileMetadata' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveMonthlyLog' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'savePlanCycle' : IDL.Func([Section, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'saveSectionTimeLog' : IDL.Func([Section, IDL.Text, IDL.Nat], [], []),
    'setCustomSubjects' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setQuestionCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setStudySession' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [], []),
    'setTargets' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Vec(SubjectTarget), IDL.Nat],
        [],
        [],
      ),
    'toggleDay' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateNotebookEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNotepadEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };