/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'targetCount' : bigint,
}
export interface ProgressEntry { 'date' : string, 'count' : bigint }
export interface _SERVICE {
  'createGoal' : ActorMethod<[string, string, bigint], Goal>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'getCompletionCount' : ActorMethod<[bigint], bigint>,
  'getEntriesForGoal' : ActorMethod<[bigint], Array<string>>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getProgressEntries' : ActorMethod<[bigint], Array<ProgressEntry>>,
  'isCompleted' : ActorMethod<[bigint, string], boolean>,
  'logCompletion' : ActorMethod<[bigint, string], undefined>,
  'updateGoal' : ActorMethod<[bigint, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];